# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyKeyboard.ui'
#
# Created: Fri Sep 23 09:29:00 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MyKeyboard(object):
    def setupUi(self, MyKeyboard):
        MyKeyboard.setObjectName(_fromUtf8("MyKeyboard"))
        MyKeyboard.resize(590, 255)
        self.pushButton = QtGui.QPushButton(MyKeyboard)
        self.pushButton.setGeometry(QtCore.QRect(59, 5, 50, 48))
        self.pushButton.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_2.setGeometry(QtCore.QRect(112, 5, 50, 48))
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_3.setGeometry(QtCore.QRect(164, 5, 50, 48))
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 5, 50, 48))
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_5.setGeometry(QtCore.QRect(217, 5, 50, 48))
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_6.setGeometry(QtCore.QRect(216, 205, 50, 48))
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_6.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_8 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_8.setGeometry(QtCore.QRect(163, 205, 50, 48))
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_8.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_12 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_12.setGeometry(QtCore.QRect(269, 55, 50, 48))
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_12.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_13.setGeometry(QtCore.QRect(322, 55, 50, 48))
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_14.setGeometry(QtCore.QRect(58, 55, 50, 48))
        self.pushButton_14.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_14.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_15.setGeometry(QtCore.QRect(5, 55, 50, 48))
        self.pushButton_15.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_15.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_19 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_19.setGeometry(QtCore.QRect(110, 55, 50, 48))
        self.pushButton_19.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_19.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_20.setGeometry(QtCore.QRect(163, 55, 50, 48))
        self.pushButton_20.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_20.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_21.setGeometry(QtCore.QRect(216, 55, 50, 48))
        self.pushButton_21.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_21.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_23 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_23.setGeometry(QtCore.QRect(482, 155, 50, 48))
        self.pushButton_23.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_23.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.pushButton_27 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_27.setGeometry(QtCore.QRect(5, 105, 50, 48))
        self.pushButton_27.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_27.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.pushButton_28 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_28.setGeometry(QtCore.QRect(58, 105, 50, 48))
        self.pushButton_28.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_28.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.pushButton_30 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_30.setGeometry(QtCore.QRect(110, 105, 50, 48))
        self.pushButton_30.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_30.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.pushButton_35 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_35.setGeometry(QtCore.QRect(58, 155, 50, 48))
        self.pushButton_35.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_35.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.pushButton_40 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_40.setGeometry(QtCore.QRect(5, 155, 50, 48))
        self.pushButton_40.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_40.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.pushButton_41 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_41.setGeometry(QtCore.QRect(429, 205, 50, 48))
        self.pushButton_41.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_41.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.pushButton_49 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_49.setGeometry(QtCore.QRect(480, 55, 102, 48))
        self.pushButton_49.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_49.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.pushButton_37 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_37.setGeometry(QtCore.QRect(110, 205, 50, 48))
        self.pushButton_37.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_37.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.pushButton_11 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_11.setGeometry(QtCore.QRect(110, 155, 50, 48))
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_11.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_18 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_18.setGeometry(QtCore.QRect(533, 205, 50, 48))
        self.pushButton_18.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_18.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_33 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_33.setGeometry(QtCore.QRect(481, 205, 50, 48))
        self.pushButton_33.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_33.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.pushButton_7 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_7.setGeometry(QtCore.QRect(163, 105, 50, 48))
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_7.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_16 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_16.setGeometry(QtCore.QRect(216, 105, 50, 48))
        self.pushButton_16.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_16.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_17.setGeometry(QtCore.QRect(269, 105, 50, 48))
        self.pushButton_17.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_17.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_22 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_22.setGeometry(QtCore.QRect(322, 105, 50, 48))
        self.pushButton_22.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_24 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_24.setGeometry(QtCore.QRect(163, 155, 50, 48))
        self.pushButton_24.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_24.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_25.setGeometry(QtCore.QRect(216, 155, 50, 48))
        self.pushButton_25.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_25.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.pushButton_26 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_26.setGeometry(QtCore.QRect(269, 155, 50, 48))
        self.pushButton_26.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_26.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_29 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_29.setGeometry(QtCore.QRect(322, 155, 50, 48))
        self.pushButton_29.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_29.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.pushButton_50 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_50.setGeometry(QtCore.QRect(5, 205, 102, 48))
        self.pushButton_50.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_50.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_50.setObjectName(_fromUtf8("pushButton_50"))
        self.pushButton_10 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_10.setGeometry(QtCore.QRect(269, 205, 50, 48))
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_10.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_31 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_31.setGeometry(QtCore.QRect(322, 205, 50, 48))
        self.pushButton_31.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_31.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.pushButton_9 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_9.setGeometry(QtCore.QRect(323, 5, 50, 48))
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_9.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_32 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_32.setGeometry(QtCore.QRect(429, 5, 50, 48))
        self.pushButton_32.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_32.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.pushButton_34 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_34.setGeometry(QtCore.QRect(376, 5, 50, 48))
        self.pushButton_34.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_34.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.pushButton_36 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_36.setGeometry(QtCore.QRect(482, 5, 50, 48))
        self.pushButton_36.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_36.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.pushButton_38 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_38.setGeometry(QtCore.QRect(375, 154, 50, 48))
        self.pushButton_38.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_38.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.pushButton_39 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_39.setGeometry(QtCore.QRect(534, 5, 50, 48))
        self.pushButton_39.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_39.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))
        self.pushButton_51 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_51.setGeometry(QtCore.QRect(480, 105, 102, 48))
        self.pushButton_51.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_51.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.pushButton_42 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_42.setGeometry(QtCore.QRect(375, 55, 50, 48))
        self.pushButton_42.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_42.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_42.setObjectName(_fromUtf8("pushButton_42"))
        self.pushButton_43 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_43.setGeometry(QtCore.QRect(375, 105, 50, 48))
        self.pushButton_43.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_43.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_43.setObjectName(_fromUtf8("pushButton_43"))
        self.pushButton_44 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_44.setGeometry(QtCore.QRect(428, 55, 50, 48))
        self.pushButton_44.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_44.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        self.pushButton_45 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_45.setGeometry(QtCore.QRect(428, 105, 50, 48))
        self.pushButton_45.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_45.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.pushButton_46 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_46.setGeometry(QtCore.QRect(6, 6, 50, 48))
        self.pushButton_46.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_46.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.pushButton_47 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_47.setGeometry(QtCore.QRect(375, 205, 50, 48))
        self.pushButton_47.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_47.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))

        self.retranslateUi(MyKeyboard)
        QtCore.QMetaObject.connectSlotsByName(MyKeyboard)

    def retranslateUi(self, MyKeyboard):
        MyKeyboard.setWindowTitle(QtGui.QApplication.translate("MyKeyboard", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MyKeyboard", "~", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MyKeyboard", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MyKeyboard", "@", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MyKeyboard", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MyKeyboard", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MyKeyboard", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MyKeyboard", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MyKeyboard", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MyKeyboard", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MyKeyboard", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MyKeyboard", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MyKeyboard", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MyKeyboard", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MyKeyboard", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MyKeyboard", "UP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_27.setText(QtGui.QApplication.translate("MyKeyboard", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_28.setText(QtGui.QApplication.translate("MyKeyboard", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_30.setText(QtGui.QApplication.translate("MyKeyboard", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_35.setText(QtGui.QApplication.translate("MyKeyboard", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_40.setText(QtGui.QApplication.translate("MyKeyboard", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_41.setText(QtGui.QApplication.translate("MyKeyboard", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_49.setText(QtGui.QApplication.translate("MyKeyboard", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_37.setText(QtGui.QApplication.translate("MyKeyboard", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MyKeyboard", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("MyKeyboard", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_33.setText(QtGui.QApplication.translate("MyKeyboard", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MyKeyboard", "{", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MyKeyboard", "}", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MyKeyboard", "[", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MyKeyboard", "]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MyKeyboard", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("MyKeyboard", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("MyKeyboard", "&lt;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_29.setText(QtGui.QApplication.translate("MyKeyboard", "&gt;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_50.setText(QtGui.QApplication.translate("MyKeyboard", "ABC", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MyKeyboard", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_31.setText(QtGui.QApplication.translate("MyKeyboard", "&amp;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MyKeyboard", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_32.setText(QtGui.QApplication.translate("MyKeyboard", "&quot;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_34.setText(QtGui.QApplication.translate("MyKeyboard", ";", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_36.setText(QtGui.QApplication.translate("MyKeyboard", "&apos;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_38.setText(QtGui.QApplication.translate("MyKeyboard", "\\", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_39.setText(QtGui.QApplication.translate("MyKeyboard", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_51.setText(QtGui.QApplication.translate("MyKeyboard", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_42.setText(QtGui.QApplication.translate("MyKeyboard", "Page\n"
"UP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_43.setText(QtGui.QApplication.translate("MyKeyboard", "Page\n"
"Donw", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_44.setText(QtGui.QApplication.translate("MyKeyboard", "Page\n"
"UP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_45.setText(QtGui.QApplication.translate("MyKeyboard", "Page\n"
"Donw", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_46.setText(QtGui.QApplication.translate("MyKeyboard", "`", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_47.setText(QtGui.QApplication.translate("MyKeyboard", "^", None, QtGui.QApplication.UnicodeUTF8))

