# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyKeyboard.ui'
#
# Created: Thu Sep 22 00:41:31 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MyKeyboard(object):
    def setupUi(self, MyKeyboard):
        MyKeyboard.setObjectName(_fromUtf8("MyKeyboard"))
        MyKeyboard.resize(585, 250)
        self.pushButton = QtGui.QPushButton(MyKeyboard)
        self.pushButton.setGeometry(QtCore.QRect(54, 2, 50, 48))
        self.pushButton.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_2.setGeometry(QtCore.QRect(107, 2, 50, 48))
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 2, 50, 48))
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_4.setGeometry(QtCore.QRect(266, 2, 50, 48))
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_5.setGeometry(QtCore.QRect(213, 2, 50, 48))
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_6.setGeometry(QtCore.QRect(319, 2, 50, 48))
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_6.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_7.setGeometry(QtCore.QRect(425, 2, 50, 48))
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_7.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_8.setGeometry(QtCore.QRect(372, 2, 50, 48))
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_8.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_9.setGeometry(QtCore.QRect(478, 2, 50, 48))
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_9.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_10.setGeometry(QtCore.QRect(532, 2, 50, 48))
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_10.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_12 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_12.setGeometry(QtCore.QRect(319, 52, 50, 48))
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_12.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_13.setGeometry(QtCore.QRect(372, 52, 50, 48))
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_14.setGeometry(QtCore.QRect(107, 52, 50, 48))
        self.pushButton_14.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_14.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_15.setGeometry(QtCore.QRect(54, 52, 50, 48))
        self.pushButton_15.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_15.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_16.setGeometry(QtCore.QRect(531, 52, 50, 48))
        self.pushButton_16.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_16.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_17.setGeometry(QtCore.QRect(425, 52, 50, 48))
        self.pushButton_17.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_17.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_19 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_19.setGeometry(QtCore.QRect(160, 52, 50, 48))
        self.pushButton_19.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_19.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_20.setGeometry(QtCore.QRect(213, 52, 50, 48))
        self.pushButton_20.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_20.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_21.setGeometry(QtCore.QRect(266, 52, 50, 48))
        self.pushButton_21.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_21.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_22.setGeometry(QtCore.QRect(478, 52, 50, 48))
        self.pushButton_22.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_23.setGeometry(QtCore.QRect(373, 102, 50, 48))
        self.pushButton_23.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_23.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.pushButton_24 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_24.setGeometry(QtCore.QRect(320, 102, 50, 48))
        self.pushButton_24.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_24.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_25.setGeometry(QtCore.QRect(426, 102, 50, 48))
        self.pushButton_25.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_25.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.pushButton_26 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_26.setGeometry(QtCore.QRect(2, 102, 101, 48))
        self.pushButton_26.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_26.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_27 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_27.setGeometry(QtCore.QRect(108, 102, 50, 48))
        self.pushButton_27.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_27.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.pushButton_28 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_28.setGeometry(QtCore.QRect(161, 102, 50, 48))
        self.pushButton_28.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_28.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.pushButton_29 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_29.setGeometry(QtCore.QRect(478, 102, 50, 48))
        self.pushButton_29.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_29.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.pushButton_30 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_30.setGeometry(QtCore.QRect(214, 102, 50, 48))
        self.pushButton_30.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_30.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.pushButton_31 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_31.setGeometry(QtCore.QRect(267, 102, 50, 48))
        self.pushButton_31.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_31.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.pushButton_33 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_33.setGeometry(QtCore.QRect(532, 102, 50, 48))
        self.pushButton_33.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_33.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.pushButton_32 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_32.setGeometry(QtCore.QRect(373, 152, 50, 48))
        self.pushButton_32.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_32.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.pushButton_34 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_34.setGeometry(QtCore.QRect(320, 152, 50, 48))
        self.pushButton_34.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_34.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.pushButton_35 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_35.setGeometry(QtCore.QRect(108, 152, 50, 48))
        self.pushButton_35.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_35.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.pushButton_36 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_36.setGeometry(QtCore.QRect(161, 152, 50, 48))
        self.pushButton_36.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_36.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.pushButton_38 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_38.setGeometry(QtCore.QRect(426, 152, 50, 48))
        self.pushButton_38.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_38.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.pushButton_40 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_40.setGeometry(QtCore.QRect(214, 152, 50, 48))
        self.pushButton_40.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_40.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.pushButton_41 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_41.setGeometry(QtCore.QRect(267, 152, 50, 48))
        self.pushButton_41.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_41.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.pushButton_42 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_42.setGeometry(QtCore.QRect(2, 152, 101, 48))
        self.pushButton_42.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_42.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_42.setObjectName(_fromUtf8("pushButton_42"))
        self.pushButton_47 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_47.setGeometry(QtCore.QRect(480, 202, 101, 48))
        self.pushButton_47.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_47.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.pushButton_53 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_53.setGeometry(QtCore.QRect(112, 202, 101, 48))
        self.pushButton_53.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_53.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_53.setObjectName(_fromUtf8("pushButton_53"))
        self.pushButton_54 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_54.setGeometry(QtCore.QRect(217, 202, 101, 48))
        self.pushButton_54.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_54.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_54.setObjectName(_fromUtf8("pushButton_54"))
        self.pushButton_55 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_55.setGeometry(QtCore.QRect(322, 202, 151, 48))
        self.pushButton_55.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_55.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_55.setObjectName(_fromUtf8("pushButton_55"))
        self.pushButton_49 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_49.setGeometry(QtCore.QRect(480, 152, 101, 48))
        self.pushButton_49.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_49.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.pushButton_56 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_56.setGeometry(QtCore.QRect(2, 202, 101, 48))
        self.pushButton_56.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_56.setMaximumSize(QtCore.QSize(500, 48))
        self.pushButton_56.setObjectName(_fromUtf8("pushButton_56"))
        self.pushButton_37 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_37.setGeometry(QtCore.QRect(2, 2, 50, 48))
        self.pushButton_37.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_37.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.pushButton_39 = QtGui.QPushButton(MyKeyboard)
        self.pushButton_39.setGeometry(QtCore.QRect(2, 51, 50, 48))
        self.pushButton_39.setMinimumSize(QtCore.QSize(50, 48))
        self.pushButton_39.setMaximumSize(QtCore.QSize(50, 48))
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))

        self.retranslateUi(MyKeyboard)
        QtCore.QMetaObject.connectSlotsByName(MyKeyboard)

    def retranslateUi(self, MyKeyboard):
        MyKeyboard.setWindowTitle(QtGui.QApplication.translate("MyKeyboard", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MyKeyboard", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MyKeyboard", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MyKeyboard", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MyKeyboard", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MyKeyboard", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MyKeyboard", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MyKeyboard", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MyKeyboard", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MyKeyboard", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MyKeyboard", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MyKeyboard", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MyKeyboard", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MyKeyboard", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MyKeyboard", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MyKeyboard", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MyKeyboard", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MyKeyboard", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MyKeyboard", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MyKeyboard", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MyKeyboard", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MyKeyboard", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MyKeyboard", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("MyKeyboard", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("MyKeyboard", "Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_27.setText(QtGui.QApplication.translate("MyKeyboard", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_28.setText(QtGui.QApplication.translate("MyKeyboard", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_29.setText(QtGui.QApplication.translate("MyKeyboard", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_30.setText(QtGui.QApplication.translate("MyKeyboard", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_31.setText(QtGui.QApplication.translate("MyKeyboard", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_33.setText(QtGui.QApplication.translate("MyKeyboard", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_32.setText(QtGui.QApplication.translate("MyKeyboard", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_34.setText(QtGui.QApplication.translate("MyKeyboard", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_35.setText(QtGui.QApplication.translate("MyKeyboard", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_36.setText(QtGui.QApplication.translate("MyKeyboard", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_38.setText(QtGui.QApplication.translate("MyKeyboard", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_40.setText(QtGui.QApplication.translate("MyKeyboard", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_41.setText(QtGui.QApplication.translate("MyKeyboard", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_42.setText(QtGui.QApplication.translate("MyKeyboard", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_47.setText(QtGui.QApplication.translate("MyKeyboard", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_53.setText(QtGui.QApplication.translate("MyKeyboard", "Ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_54.setText(QtGui.QApplication.translate("MyKeyboard", "Alt", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_55.setText(QtGui.QApplication.translate("MyKeyboard", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_49.setText(QtGui.QApplication.translate("MyKeyboard", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_56.setText(QtGui.QApplication.translate("MyKeyboard", "ChangePage", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_37.setText(QtGui.QApplication.translate("MyKeyboard", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_39.setText(QtGui.QApplication.translate("MyKeyboard", "Home", None, QtGui.QApplication.UnicodeUTF8))

